### PR TITLE
embedded-YouTube-video-in-page

### PR DESCRIPTION
**Pull request by uszilard**
managed to embed the YouTube video into the relevant container, search function work

### CODE REVIEW

**Comment by hristina-staykova** [comment]
"This branch has conflicts that must be resolved" - what to do?

**Comment by uszilard** [comment]
can you check where is the conflict , i made some changes to the html, because the drop down many had to be changed to a check box stile

**Comment by uszilard** [comment]
@tonysaad how to best manage a conflict ?

**Comment by hristina-staykova** [comment]
I see two conflicts now - index.html & napsterapi.js 
How to solve them? I mean I don't know how and what to do, really. I don't see an option here to change anything. Is it possible to delete this pull request and create a new one without these conflicts?
Also, as far as I see, your edits in napster.js overwrite everything I've written and if I accept it, it will be only one console.log of results, is that right? @uszilard

**Review by hristina-staykova — APPROVED** [review]
Let's hope it's okay

**Pull request merged**
